version: "3.8"
services:
  app:
    build: .
    depends_on:
      - db
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules

  db:
    image: postgres:14.1-alpine
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      # Postgres will run then initdb.sql script when started
      - ./backend/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
      - ./backend/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


