version: "3.8"
services:
  app:
    build: .
    depends_on:
      - db
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules

  db:
    image: postgres:14.1-alpine
    env_file: .env
    volumes:
      # Postgres will run then initdb.sql script when started
      - "dbdata:/var/lib/postgresql/data"
      - ./backend/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
      
    ports:
      - "5432:5432"

volumes:
  dbdata:


